{% set name = "curve_visualizer" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
# https://github.com/RandDouble/Curve_Visualizer/releases/download/v0.0.2/curve_visualizer-0.0.2.tar.gz
  url: https://github.com/RandDouble/Curve_Visualizer/releases/download/v{{ version }}/curve_visualizer-{{ version }}.tar.gz
  sha256: 124c8cf2706cf19ceebfd4430b2802873175c864836d3d73bdc80aed6d22e6a0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - upDatabase = curve_visualizer.upDatabase:main
    - curve_visualizer = curve_visualizer.curve_visualizer:main

requirements:
  host:
    - setuptools >=68.0
    - setuptools-scm >6
    - pip
    - python >=3.12
  run:
    - python      >=3.12
    - pip
    - numpy       1.26
    - matplotlib  3.8
    - pandas      >=2.0
    - pyside6      6.6.0
    - qt6-main    6.6.0
   
test:
  commands:
    - upDatabase --help

about:
  home: "https://github.com/RandDouble/Curve_Visualizer"
  summary: Package for creation of a Database and Data visualization
  dev_url: "https://github.com/RandDouble/Curve_Visualizer"
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RandDouble
