# {% set pyproject = load_file_data('pyproject.toml') %}
{% set name = "curve_visualizer" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
# https://github.com/RandDouble/Curve_Visualizer/releases/download/v0.0.2/curve_visualizer-0.0.2.tar.gz
  url: https://github.com/RandDouble/Curve_Visualizer/releases/download/v{{ version }}/curve_visualizer-{{ version }}.tar.gz
  sha256:  68de705bad5aece4d6a8d4e07aa9b248aca75bbaf3763ee848d1ab0a6085bf62

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  entry_points:
    - upDatabase = curve_visualizer.upDatabase:main
    - curve_visualizer = curve_visualizer.curve_visualizer:main

requirements:
  host:
    - setuptools >=68.0
    - setuptools-scm >6
    - pip
    - python >=3.12
    - wheel
  run:
    - python      >=3.12
    - pip
    - numpy       >=1.26
    - matplotlib  >=3.8
    - pandas      >=2.0
    - pyside6      6.6.0
    - qt6-main    6.6.0
    - scipy       >=1.11
    - scikit-learn >=1.3


# test:
#   requires: 
#     - pip
#   commands:
#     - pip check
#     - upDatabase --help

about:
  home: "https://github.com/RandDouble/Curve_Visualizer"
  summary: Package for creation of a Database and Data visualization
  dev_url: "https://github.com/RandDouble/Curve_Visualizer"
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RandDouble
